### ISSUE TITLE
Make namespace usage consistent for more classes

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/PyDataGlobal2020-sprint#1]
This PR involves:

## 1. change `scripts/check_for_inconsistent_pandas_namespace.py` to

```python
"""
Check that test suite file doesn't use the pandas namespace inconsistently.

We check for cases of ``Series`` and ``pd.Series`` appearing in the same file
(likewise for some other common classes).

This is meant to be run as a pre-commit hook - to run it manually, you can do:

    pre-commit run inconsistent-namespace-usage --all-files
"""

import argparse
from pathlib import Path
import re
from typing import Optional, Sequence

PATTERN = r"""
    (
        (?<!pd\.)(?<!\w)    # check class_name start with pd. or character
        ([A-Z]\w+)\(      # match DataFrame but not pd.DataFrame or tm.makeDataFrame
        .*                  # match anything
        pd\.\2\(  # only match e.g. pd.DataFrame
    )|
    (
        pd\.([A-Z]\w+)\(  # only match e.g. pd.DataFrame
        .*                  # match anything
        (?<!pd\.)(?<!\w)    # check class_name start with pd. or character
        \4\(      # match DataFrame but not pd.DataFrame or tm.makeDataFrame
    )
    """
ERROR_MESSAGE = "Found both `pd.{class_name}` and `{class_name}` in {path}"


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*", type=Path)
    args = parser.parse_args(argv)

    pattern = re.compile(
        PATTERN.encode(),
        flags=re.MULTILINE | re.DOTALL | re.VERBOSE,
    )
    for path in args.paths:
        contents = path.read_bytes()
        match = pattern.search(contents)
        if match is None:
            continue
        if match.group(2) is not None:
            raise AssertionError(
                ERROR_MESSAGE.format(class_name=match.group(2).decode(), path=str(path))
            )
        if match.group(4) is not None:
            raise AssertionError(
                ERROR_MESSAGE.format(class_name=match.group(4).decode(), path=str(path))
            )


if __name__ == "__main__":
    main()
```

## 3. fixup errors

**Comment by lpkirwin** [comment]
I'll take this one 👍

**Comment by MarcoGorelli** [comment]
> I'll take this one +1

OK, please comment which files you're taking

**Comment by MarcoGorelli** [comment]
```
AssertionError: Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/datetimes/test_constructors.py
Traceback (most recent call last):
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 59, in <module>
    main()
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 49, in main
    raise AssertionError(
AssertionError: Found both `pd.RangeIndex` and `RangeIndex` in pandas/tests/frame/test_constructors.py
Traceback (most recent call last):
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 59, in <module>
    main()
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 49, in main
    raise AssertionError(
AssertionError: Found both `pd.Float64Index` and `Float64Index` in pandas/tests/indexes/test_numeric.py
Traceback (most recent call last):
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 59, in <module>
    main()
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 53, in main
    raise AssertionError(
AssertionError: Found both `pd.Period` and `Period` in pandas/tests/reductions/test_reductions.py
Traceback (most recent call last):
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 59, in <module>
    main()
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 49, in main
    raise AssertionError(
AssertionError: Found both `pd.HDFStore` and `HDFStore` in pandas/tests/io/pytables/test_store.py
Traceback (most recent call last):
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 59, in <module>
    main()
  File "scripts/check_for_inconsistent_pandas_namespace.py", line 49, in main
    raise AssertionError(
AssertionError: Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_dtype.py
```

**Comment by lpkirwin** [comment]
I'll start by fixing these:

```
AssertionError: Found both `pd.Period` and `Period` in pandas/tests/resample/test_period_index.py
AssertionError: Found both `pd.Float64Index` and `Float64Index` in pandas/tests/arithmetic/conftest.py
AssertionError: Found both `pd.Period` and `Period` in pandas/tests/arithmetic/test_datetime64.py
AssertionError: Found both `pd.Grouper` and `Grouper` in pandas/tests/resample/test_datetime_index.py
AssertionError: Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/datetimes/test_constructors.py
AssertionError: Found both `pd.Int64Dtype` and `Int64Dtype` in pandas/tests/arrays/integer/test_construction.py
AssertionError: Found both `pd.Period` and `Period` in pandas/tests/reductions/test_reductions.py
AssertionError: Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_array.py
```

**Comment by lpkirwin** [comment]
Above are all done, now moving on to:

```
AssertionError: Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexing/test_categorical.py
AssertionError: Found both `pd.ExcelFile` and `ExcelFile` in pandas/tests/io/excel/test_xlrd.py
AssertionError: Found both `pd.DateOffset` and `DateOffset` in pandas/tests/arithmetic/test_datetime64.py
AssertionError: Found both `pd.Period` and `Period` in pandas/tests/resample/test_datetime_index.py
AssertionError: Found both `pd.RangeIndex` and `RangeIndex` in pandas/tests/frame/test_constructors.py
AssertionError: Found both `pd.Float64Index` and `Float64Index` in pandas/tests/indexes/test_numeric.py
AssertionError: Found both `pd.Grouper` and `Grouper` in pandas/tests/reshape/test_pivot.py
AssertionError: Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/extension/test_sparse.py
```

**Comment by jan-mue** [comment]
I think the remaining ones are
```
Found both `pd.Interval` and `Interval` in pandas/tests/arithmetic/test_interval.py
Found both `pd.PeriodIndex` and `PeriodIndex` in pandas/tests/indexes/period/test_ops.py
Found both `pd.Grouper` and `Grouper` in pandas/tests/groupby/test_groupby.py
Found both `pd.Interval` and `Interval` in pandas/tests/indexes/interval/test_interval.py
Found both `pd.Grouper` and `Grouper` in pandas/tests/groupby/test_timegrouper.py
Found both `pd.Int64Index` and `Int64Index` in pandas/tests/arithmetic/test_numeric.py
Found both `pd.RangeIndex` and `RangeIndex` in pandas/tests/series/test_constructors.py
Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/categorical/test_map.py
Found both `pd.Interval` and `Interval` in pandas/tests/arrays/categorical/test_constructors.py
Found both `pd.Period` and `Period` in pandas/tests/dtypes/test_inference.py
```
and
```
Found both `pd.Period` and `Period` in pandas/tests/scalar/period/test_period.py
Found both `pd.Float64Index` and `Float64Index` in pandas/tests/indexes/test_base.py
Found both `pd.Period` and `Period` in pandas/tests/arithmetic/test_period.py
Found both `pd.Float64Dtype` and `Float64Dtype` in pandas/tests/arrays/floating/test_construction.py
Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/categorical/test_indexing.py
Found both `pd.RangeIndex` and `RangeIndex` in pandas/tests/indexes/ranges/test_indexing.py
Found both `pd.HDFStore` and `HDFStore` in pandas/tests/io/pytables/test_store.py
Found both `pd.Period` and `Period` in pandas/tests/arrays/test_datetimelike.py
Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_dtype.py
Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/categorical/test_formats.py
```
I'll have a look at the latter half.

**Comment by MarcoGorelli** [comment]
cool! make sure to not include the modifications to `scripts/check_for_inconsistent_pandas_namespace.py` in your PR, we'll change that one at the end

**Comment by christopherhadley** [comment]
I'm working my way through the first list in @jan-mue 's list above - so that's these:

Found both `pd.Interval` and `Interval` in pandas/tests/arithmetic/test_interval.py
Found both `pd.PeriodIndex` and `PeriodIndex` in pandas/tests/indexes/period/test_ops.py
Found both `pd.Grouper` and `Grouper` in pandas/tests/groupby/test_groupby.py
Found both `pd.Interval` and `Interval` in pandas/tests/indexes/interval/test_interval.py
Found both `pd.Grouper` and `Grouper` in pandas/tests/groupby/test_timegrouper.py
Found both `pd.Int64Index` and `Int64Index` in pandas/tests/arithmetic/test_numeric.py
Found both `pd.RangeIndex` and `RangeIndex` in pandas/tests/series/test_constructors.py
Found both `pd.CategoricalIndex` and `CategoricalIndex` in pandas/tests/indexes/categorical/test_map.py
Found both `pd.Interval` and `Interval` in pandas/tests/arrays/categorical/test_constructors.py
Found both `pd.Period` and `Period` in pandas/tests/dtypes/test_inference.py

**Comment by reshamas** [comment]
I am giving this file a try:
Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_dtype.py

**Comment by jan-mue** [comment]
> I am giving this file a try:
> Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_dtype.py

This should already be in my PR

**Comment by reshamas** [comment]
> > I am giving this file a try:
> > Found both `pd.SparseDtype` and `SparseDtype` in pandas/tests/arrays/sparse/test_dtype.py
> 
> This should already be in my PR

We can close my PR.  My goal was to go through the process.

**Comment by reshamas** [comment]
I am trying this one file
```text
Found both `pd.Interval` and `Interval` in pandas/tests/arithmetic/test_interval.py
```

**Comment by christopherhadley** [comment]
I made a PR for the files I edited: https://github.com/pandas-dev/pandas/pull/37852

I'd be happy to continue working on any changes required either tomorrow or next week. Thank you!

**Comment by MarcoGorelli** [comment]
Hi all,

here's a good issue to work on in case you fancy doing any more pandas-dev/pandas#30999

**Comment by MarcoGorelli** [comment]
This script is now part of the pandas CI process, thanks all for your help :tada:
